from io import BytesIO
from datetime import datetime
from fpdf import FPDF


def _safe(text: str) -> str:
    return text.encode("latin-1", errors="replace").decode("latin-1")


class ReportPDF(FPDF):
    def header(self):
        if self.page_no() > 1:
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(120, 120, 120)
            self.cell(0, 8, "VoiceHire AI Interview Report", align="L")
            self.cell(0, 8, f"Session {self.session_id}", align="R", new_x="LMARGIN", new_y="NEXT")
            self.line(10, 16, 200, 16)
            self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}  |  Generated by VoiceHire - Band of Agents Hackathon 2026", align="C")


def _coverage_bar(pdf: FPDF, label: str, covered: int, total: int, width: int = 80):
    if total == 0:
        pct = 0
    else:
        pct = covered / total
    pdf.set_font("Helvetica", "", 9)
    pdf.cell(60, 6, label, align="L")
    pdf.set_fill_color(230, 230, 230)
    pdf.rect(pdf.get_x(), pdf.get_y(), width, 6, style="F")
    fill_color = (34, 197, 94) if pct >= 0.8 else (234, 179, 8) if pct >= 0.5 else (239, 68, 68)
    pdf.set_fill_color(*fill_color)
    pdf.rect(pdf.get_x(), pdf.get_y(), int(width * pct), 6, style="F")
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(0, 6, f"  {covered}/{total}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)


def generate_pdf(
    session_id: str,
    session_info: dict | None = None,
    report: dict | None = None,
    decision: dict | None = None,
    deliberation_text: dict | None = None,
) -> bytes:
    pdf = ReportPDF()
    pdf.session_id = session_id
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # ── Title block ──
    pdf.set_font("Helvetica", "B", 24)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 14, "VoiceHire", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 14)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 8, "AI Interview Report", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 5, f"Session ID: {session_id}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 5, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)

    # ── Session metadata ──
    if session_info:
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(0, 7, "Session Info", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(60, 60, 60)
        info_lines = [
            ("Status", session_info.get("status", "N/A")),
            ("Candidate", session_info.get("candidate_name") or "-"),
            ("Email", session_info.get("candidate_email") or "-"),
            ("Enforcement Level", session_info.get("enforcement_config", {}).get("level", "N/A")),
            ("Demo Mode", str(session_info.get("enforcement_config", {}).get("demo_mode", False))),
            ("Violations", str(len(session_info.get("integrity_violations", [])))),
        ]
        for label, value in info_lines:
            pdf.set_font("Helvetica", "", 9)
            pdf.cell(40, 5, label, align="L")
            pdf.set_font("Helvetica", "B", 9)
            pdf.cell(0, 5, value, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)

    # ── Hiring Verdict ──
    if decision:
        rec = decision.get("final_recommendation", "N/A")
        rec_colors = {
            "STRONG_HIRE": (22, 163, 74),
            "HIRE": (34, 197, 94),
            "NO_HIRE": (239, 68, 68),
            "STRONG_NO_HIRE": (185, 28, 28),
        }
        color = rec_colors.get(rec, (100, 100, 100))
        pdf.set_fill_color(*color)
        pdf.rect(10, pdf.get_y(), 190, 12, style="F")
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(0, 12, f"  {rec.replace('_', ' ')}", new_x="LMARGIN", new_y="NEXT", align="C")
        pdf.ln(3)
        pdf.set_text_color(60, 60, 60)
        pdf.set_font("Helvetica", "", 9)
        pdf.cell(0, 5, f"Consensus Reached: {'Yes' if decision.get('consensus_reached') else 'No'}", new_x="LMARGIN", new_y="NEXT")
        pdf.cell(0, 5, f"Model: {decision.get('model_used', 'N/A')}", new_x="LMARGIN", new_y="NEXT")
        must_total = decision.get("must_have_total", 0)
        must_demo = decision.get("must_have_demonstrated", 0)
        pdf.cell(0, 5, f"Must-Have Competencies Demonstrated: {must_demo}/{must_total}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)

    # ── Coverage Summary ──
    if report and report.get("coverage_summary"):
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(0, 7, "Coverage Summary", new_x="LMARGIN", new_y="NEXT")
        cs = report["coverage_summary"]
        _coverage_bar(pdf, "All Competencies", cs.get("covered", 0), cs.get("total", 0))
        _coverage_bar(pdf, "Must-Have", cs.get("must_have_covered", 0), cs.get("must_have_total", 0))
        pdf.ln(2)

    # ── Competency Scorecard ──
    if report and report.get("competency_scorecard"):
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(0, 7, "Competency Scorecard", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(1)

        # Table header
        col_w = [40, 28, 28, 28, 22, 22]
        headers = ["Competency", "Domain", "Class", "Status", "Conf.", "Evid."]
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_fill_color(240, 240, 240)
        for i, h in enumerate(headers):
            pdf.cell(col_w[i], 6, h, border=1, align="C", fill=True)
        pdf.ln()

        status_colors = {
            "COVERED": (220, 252, 231),
            "WEAK": (254, 249, 195),
            "UNEXPLORED": (243, 244, 246),
            "INSUFFICIENT": (254, 226, 226),
            "EXHAUSTED": (219, 234, 254),
        }

        pdf.set_font("Helvetica", "", 7.5)
        for c in report["competency_scorecard"]:
            row_h = 5
            x_start = pdf.get_x()
            y_start = pdf.get_y()

            bg = status_colors.get(c.get("status", ""), (255, 255, 255))
            pdf.set_fill_color(*bg)
            for i, key in enumerate(["name", "domain", "classification", "status", "confidence", "evidence_count"]):
                val = str(c.get(key, ""))
                if key == "confidence":
                    val = f"{val}%"
                pdf.cell(col_w[i], row_h, val, border=1, align="C", fill=True)
            pdf.ln()

            # Per-competency verdict from committee
            if decision and decision.get("competency_verdicts"):
                cv = decision["competency_verdicts"].get(c.get("id", ""))
                if cv:
                    pdf.set_x(x_start + 2)
                    pdf.set_font("Helvetica", "I", 7)
                    pdf.set_text_color(100, 100, 100)
                    depth = cv.get("depth_reached", "")
                    integrity_flag = " [INTEGRITY FLAGGED]" if cv.get("integrity_flagged") else ""
                    pdf.cell(0, 4, f"Verdict: {cv.get('verdict', '')}  |  Depth: {depth}{integrity_flag}", new_x="LMARGIN", new_y="NEXT")
                    pdf.set_text_color(60, 60, 60)

            # Check if we need a new page
            if pdf.get_y() > 255:
                pdf.add_page()
        pdf.ln(4)

    # ── Evidence Portfolio ──
    if report and report.get("evidence_portfolio"):
        evidence = report["evidence_portfolio"]
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(0, 7, f"Evidence Portfolio ({len(evidence)} items)", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(1)

        for i, ev in enumerate(evidence):
            if pdf.get_y() > 240:
                pdf.add_page()

            pdf.set_font("Helvetica", "B", 8)
            pdf.set_fill_color(245, 245, 250)
            pdf.cell(0, 5, f"Evidence #{i + 1}  |  {ev.get('source_type', 'VERBAL_RESPONSE')}", fill=True, new_x="LMARGIN", new_y="NEXT")

            # Transcript
            transcript = ev.get("raw_transcript", "")
            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(40, 40, 40)
            pdf.multi_cell(0, 4, _safe(transcript[:600]))
            pdf.ln(1)

            # Tags
            comp_tags = ev.get("competencies_tagged", [])
            behav_tags = ev.get("behavioral_tags", [])
            if comp_tags:
                pdf.set_font("Helvetica", "I", 7)
                pdf.set_text_color(80, 80, 80)
                tags_str = " | ".join(
                    f"{t.get('competency_id', '?')} ({t.get('confidence', 0):.0%}, {t.get('polarity', '')})"
                    for t in comp_tags
                )
                pdf.cell(0, 4, f"Competency Tags: {tags_str}", new_x="LMARGIN", new_y="NEXT")
            if behav_tags:
                pdf.set_font("Helvetica", "I", 7)
                pdf.set_text_color(80, 80, 80)
                tags_str = " | ".join(
                    f"{t.get('tag', '?')} ({t.get('confidence', 0):.0%}, {t.get('polarity', '')})"
                    for t in behav_tags
                )
                pdf.cell(0, 4, f"Behavioral Tags: {tags_str}", new_x="LMARGIN", new_y="NEXT")

            # Signals / Skills
            signals = ev.get("extracted_signals", [])
            skills = ev.get("demonstrated_skills", [])
            missed = ev.get("missed_signals", [])
            if signals:
                pdf.cell(0, 4, f"Signals: {', '.join(signals[:5])}", new_x="LMARGIN", new_y="NEXT")
            if skills:
                pdf.cell(0, 4, f"Skills: {', '.join(skills[:5])}", new_x="LMARGIN", new_y="NEXT")
            if missed:
                pdf.cell(0, 4, f"Missed: {', '.join(missed[:3])}", new_x="LMARGIN", new_y="NEXT")

            # Confidence / ownership
            overall_conf = ev.get("overall_confidence", 0)
            ownership = ev.get("ownership_score", 0)
            pdf.set_font("Helvetica", "", 7)
            pdf.set_text_color(100, 100, 100)
            pdf.cell(0, 4, f"Confidence: {overall_conf:.0%}  |  Ownership: {ownership:.0%}", new_x="LMARGIN", new_y="NEXT")
            pdf.ln(2)

        pdf.ln(2)

    # ── Deliberation Transcript ──
    if deliberation_text:
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(0, 7, "Deliberation Transcript", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(1)

        for role in ("advocate", "critic"):
            text = deliberation_text.get(role, "")
            if not text:
                continue
            if pdf.get_y() > 240:
                pdf.add_page()

            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(40, 40, 40)
            pdf.cell(0, 5, f"--- {role.title()} ---", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(60, 60, 60)
            pdf.multi_cell(0, 4, _safe(text[:2000]))
            pdf.ln(3)

        if decision and decision.get("deliberation_transcript"):
            dt = decision["deliberation_transcript"]
            pdf.ln(1)
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(40, 40, 40)
            pdf.cell(0, 5, "--- Advocate (truncated) ---", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(60, 60, 60)
            pdf.multi_cell(0, 4, _safe(dt.get("advocate", "")[:1000]))
            pdf.ln(1)
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(40, 40, 40)
            pdf.cell(0, 5, "--- Critic (truncated) ---", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(60, 60, 60)
            pdf.multi_cell(0, 4, _safe(dt.get("critic", "")[:1000]))

        pdf.ln(4)

    # ── Evidence Gaps ──
    if decision and decision.get("evidence_gaps"):
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(0, 7, "Evidence Gaps", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(60, 60, 60)
        for gap in decision["evidence_gaps"]:
            pdf.cell(0, 5, f"  - {gap}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)

    # ── Integrity Violations ──
    if session_info:
        violations = session_info.get("integrity_violations", [])
        if violations:
            if pdf.get_y() > 230:
                pdf.add_page()
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(30, 30, 30)
            pdf.cell(0, 7, f"Integrity Violations ({len(violations)})", new_x="LMARGIN", new_y="NEXT")
            pdf.ln(1)

            col_w = [40, 50, 30, 20]
            pdf.set_font("Helvetica", "B", 8)
            pdf.set_fill_color(240, 240, 240)
            for i, h in enumerate(["Timestamp", "Type", "Severity", "Points"]):
                pdf.cell(col_w[i], 5, h, border=1, align="C", fill=True)
            pdf.ln()

            pdf.set_font("Helvetica", "", 7.5)
            for v in violations:
                ts = v.get("timestamp", 0)
                if ts > 1e12:
                    ts_str = datetime.fromtimestamp(ts / 1000).strftime("%H:%M:%S")
                else:
                    ts_str = datetime.fromtimestamp(ts).strftime("%H:%M:%S")
                vals = [ts_str, v.get("type", "").replace("_", " "), v.get("severity", "").upper(), str(v.get("points", 0))]
                for i, val in enumerate(vals):
                    pdf.cell(col_w[i], 5, val, border=1, align="C")
                pdf.ln()

    buf = BytesIO()
    pdf.output(buf)
    return buf.getvalue()
